FROM ubuntu:22.04

RUN apt-get update && apt-get install -y build-essential \
	libreadline-dev

COPY ./libft ./libft
COPY ./ft_printf ./ft_printf
COPY ./get_next_line ./get_next_line
COPY ./pushswap ./pushswap
COPY ./minishell ./minishell
COPY ./philosophers ./philosophers
