FROM alpine:3.17.1

RUN apk add --no-cache build-base \
	readline-dev

COPY ./libft ./libft
COPY ./ft_printf ./ft_printf
COPY ./get_next_line ./get_next_line
COPY ./pushswap ./pushswap
COPY ./minishell ./minishell
COPY ./philosophers ./philosophers
