version: "3"

services:

  nginx:
    restart: always
    container_name: nginx
    hostname: nginx
    build: requirements/nginx
    image: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html

  wordpress:
    restart: always
    image: wordpress
    container_name: wordpress
    depends_on:
      - vsftpd
      - mariadb
    hostname: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    environment:
      WORDPRESS_URL:             ${WORDPRESS_URL}
      WORDPRESS_TITLE:           ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN:           ${WORDPRESS_ADMIN}
      WORDPRESS_ADMIN_PASSWORD:  ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL:     ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_DATABASE_NAME:   ${WORDPRESS_DATABASE_NAME}
      WORDPRESS_USER:            ${WORDPRESS_USER}
      WORDPRESS_USER_EMAIL:      ${WORDPRESS_USER_EMAIL}
      WORDPRESS_USER_ROLE:       ${WORDPRESS_USER_ROLE}
      WORDPRESS_USER_PASSWORD:   ${WORDPRESS_USER_PASSWORD}
      MARIADB_USER:              ${MARIADB_USER}
      MARIADB_USER_PASSWORD:     ${MARIADB_USER_PASSWORD}
      WORDPRESS_DATABASE_NAME:   ${WORDPRESS_DATABASE_NAME}
      MARIADB_HOST_NAME:         ${MARIADB_HOST_NAME}
      VSFPTD_USER:               ${VSFPTD_USER}
      VSFPTD_PASSWORD:           ${VSFPTD_PASSWORD}
      VSFPTD_HOST:               ${VSFPTD_HOST}

  mariadb:
    restart: always
    container_name: mariadb
    hostname: mariadb
    image: mariadb
    volumes:
      - mariadb_vol:/var/lib/mysql
    build: requirements/mariadb
    networks:
      - inception
    environment:
      MARIADB_USER:              ${MARIADB_USER}
      MARIADB_USER_PASSWORD:     ${MARIADB_USER_PASSWORD}
      WORDPRESS_DATABASE_NAME:   ${WORDPRESS_DATABASE_NAME}
      MARIADB_ROOT_PASSWORD:     ${MARIADB_ROOT_PASSWORD}

  vsftpd:
    restart: always
    image: vsftpd
    container_name: vsftpd
    hostname: vsftpd
    build: requirements/bonus/vsftpd
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    environment:
      VSFPTD_USER:               ${VSFPTD_USER}
      VSFPTD_PASSWORD:           ${VSFPTD_PASSWORD}
    ports:
      - "21:21"
      - "21100-21110:21100-21110"

networks:
  inception:
    driver: bridge
    name: inception

volumes:
  wordpress_vol:
    driver: local
    name: wordpress_vol
    driver_opts:
      type: none 
      o: bind
      device: '${HOME}/data/wordpress'
  mariadb_vol:
    driver: local
    name: maraidb_vol
    driver_opts:
      type: none 
      o: bind
      device: '${HOME}/data/mariadb'
