version: '2.4'

services:

  nginx:
    restart: always
    container_name: nginx
    hostname: nginx
    build: requirements/nginx
    image: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - ./wordpress_vol/:/var/www/html/:delegated

  wordpress:
    restart: always
    image: wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    hostname: wordpress
    build: requirements/wordpress
    volumes:
      - ./wordpress_vol/:/var/www/html/:delegated
    networks:
      - inception
    environment:
      WORDPRESS_URL:             ${WORDPRESS_URL}
      WORDPRESS_TITLE:           ${WORDPRESS_TITLE}
      WORDPRESS_ADMIN:           ${WORDPRESS_ADMIN}
      WORDPRESS_ADMIN_PASSWORD:  ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL:     ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_DATABASE_NAME:   ${WORDPRESS_DATABASE_NAME}
      WORDPRESS_USER:            ${WORDPRESS_USER}
      WORDPRESS_USER_EMAIL:      ${WORDPRESS_USER_EMAIL}
      WORDPRESS_USER_ROLE:       ${WORDPRESS_USER_ROLE}
      WORDPRESS_USER_PASSWORD:   ${WORDPRESS_USER_PASSWORD}
      MARIADB_USER:              ${MARIADB_USER}
      MARIADB_USER_PASSWORD:     ${MARIADB_USER_PASSWORD}
      WORDPRESS_DATABASE_NAME:   ${WORDPRESS_DATABASE_NAME}
      MARIADB_HOST_NAME:         ${MARIADB_HOST_NAME}
      VSFPTD_USER:               ${VSFPTD_USER}
      VSFPTD_PASSWORD:           ${VSFPTD_PASSWORD}
      VSFPTD_HOST:               ${VSFPTD_HOST}

  mariadb:
    restart: always
    container_name: mariadb
    hostname: mariadb
    image: mariadb
    volumes:
      - ./mairdb_vol/:/var/lib/mysql/:delegated
    build: requirements/mariadb
    networks:
      - inception
    environment:
      MARIADB_USER:              ${MARIADB_USER}
      MARIADB_USER_PASSWORD:     ${MARIADB_USER_PASSWORD}
      WORDPRESS_DATABASE_NAME:   ${WORDPRESS_DATABASE_NAME}
      MARIADB_ROOT_PASSWORD:     ${MARIADB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "-uroot", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 3s

  vsftpd:
    restart: always
    image: vsftpd
    container_name: vsftpd
    hostname: vsftpd
    build: requirements/bonus/vsftpd
    volumes:
      - ./wordpress_vol/:/var/www/html/:delegated
    networks:
      - inception
    depends_on:
      - wordpress
    environment:
      VSFPTD_USER:               ${VSFPTD_USER}
      VSFPTD_PASSWORD:           ${VSFPTD_PASSWORD}
    ports:
      - "21:21"
      - "21100-21110:21100-21110"

networks:
  inception:
    driver: bridge
    name: inception
