# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: alkrusts <alkrust@student.codam.nl>          +#+                      #
#                                                    +#+                       #
#    Created: 2021/04/30 12:25:04 by alkrusts      #+#    #+#                  #
#    Updated: 2021/04/30 12:25:05 by alkrusts      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

all:
	gcc norm_calc.c -L../libs/libft -lft -o norm
clean:
	rm -rf norm
